### ISSUE TITLE
Allow PROMPT_COMMAND to invoke a function

### ISSUE THREAD

**Issue by chmaynard** [dotslash/recent2#32]
I'd like to do the following in .bashrc:

```
log_on_success() {
	if [ $? -eq 0 ]
	then
        log-recent -r $? -c "$(HISTTIMEFORMAT= history 1)" -p $$
    fi
}

export PROMPT_COMMAND='log_on_success'
```

When I invoke the recent command, I get this error:

```
$ recent -h
PROMPT_COMMAND env variable is not set. Add the following line to .bashrc or .bash_profile
export PROMPT_COMMAND='log-recent -r $? -c "$(HISTTIMEFORMAT= history 1)" -p $$' 
```

**Comment by dotslash** [comment]
Thanks for reaching out. 
This is an interesting usecase. I will do that in the next 1 week

**Comment by chmaynard** [comment]
Lovely. I'm looking forward to trying this out.

**Comment by dotslash** [comment]
Set RECENT_CUSTOM_PROMPT=1 (or any non empty value)

That will allow you set PROMPT_COMMAND to whatever you want.

**Comment by chmaynard** [comment]
Works well, thanks.

In the FAQ, I recommend this tweak:
I want to have a custom PROMPT_COMMAND that calls **log-recent** using my own logic.
