### ISSUE TITLE
Add support for zsh

### ISSUE THREAD

**Issue by andrei-assa** [dotslash/recent2#59]
**Describe the bug**
Logging does not occur correctly when using zsh instead of bash.

**To Reproduce**
1. `pip install recent2`
2. Add `export PROMPT_COMMAND='log-recent -r $? -c "$(HISTTIMEFORMAT= history 1)" -p $$'` to .zshrc
3. Start new shell
4. 
```bash
$ recent
# Output:

PROMPT_COMMAND env variable is not set. Add the following line to .bashrc or .bash_profile
export PROMPT_COMMAND='log-recent -r $? -c "$(HISTTIMEFORMAT= history 1)" -p $$'
```

**Expected behavior**
```bash
$ recent
# Output:
recent: building schema
```

**Desktop**
Darwin MacBook-Pro.lan 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:14 PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64 x86_64

**Comment by dotslash** [comment]
yeah. zsh does not work at this moment. 

Given that I use bash, never found motivation to support other shells. But i believe it should not be hard to add support. If you like the idea of recent2 and want to use it with zsh, I can give it a shot.

**Comment by andrei-assa** [comment]
Hi, thanks for taking a look at this issue, would be happy to work on this with you, zsh support would be great to implement, I think.
