### ISSUE TITLE
Feature improvements and enhancements for recent2.

### ISSUE THREAD

**Issue by hongyi-zhao** [dotslash/recent2#60]
On Ubuntu 20.04.2 LTS, I use the [recent2](https://github.com/dotslash/recent2/blob/master/recent2.py) to log and query my bash history, which uses a sqlite3 database to store the history information. The `datetime` of running a command is inserted in the sqlite3 database with [a `unixepoch` format](https://github.com/dotslash/recent2/blob/f1018aee228c710cc7d1b8b93bc0228791a54563/recent2.py#L45), and it will be converted into `localtime` accordingly when retrieved and displayed later.

But I found that it did not perform the correct conversion according to the time zone setting on the machine, as shown below:
```shell
werner@X10DAi-00:~$ rm 222222222222222222
rm: cannot remove '222222222222222222': No such file or directory
werner@X10DAi-00:~$ recent -fo -w . 2222222222222
rm 222222222222222222                              # rtime@ 2021-08-29 10:57:13
werner@X10DAi-00:~$ date 
Sun 29 Aug 2021 06:57:22 PM CST
```
I also filed an issue [here](https://discuss.python.org/t/python-sqlite3-datetime-verconsion-between-unixepoch-and-localtime/10382). Any hints for this problem?

Regards,
HY

**Comment by hongyi-zhao** [comment]
I fixed this [problem](https://github.com/hongyi-zhao/recent2/commit/0b7306be7100c5decbfc4ffda297ab3bc4111ae6).

**Comment by dotslash** [comment]
Thanks for the fix.  I'm reopening so that I can merge your fix.

**Comment by hongyi-zhao** [comment]
I've also added some other improvements and enhancements, including added short keys for all options, as shown below: 

```
$ recent -h
usage: recent [-h] [-n NUM] [--exit_code CODE] [--failure] [-d DIR] [--cur_session]
              [-D DATE] [--self] [--limit LIMIT] [--env key[:val]] [--dedup] [--time_hide]
              [--debug] [--detail] [--columns COL] [-re] [-sql] [--insensitive]
              [pattern]

recent is a convenient way to query bash history. Visit
https://github.com/dotslash/recent2 for more examples or to ask questions or to
report issues

positional arguments:
  pattern               optional pattern to search

optional arguments:
  -h, --help            show this help message and exit
  -n NUM                max results to return
  --exit_code CODE, -e CODE
                        int exit status of the commands to return. -1 => return all.
  --failure, -f         only return commands that exited with failure
  -d DIR                The Directory where the command runs
  --cur_session, -c     Returns commands only from current session
  -D DATE               date in YYYY, YYYY-MM, or YYYY-MM-DD formats
  --self, -S            Return `recent` commands also in the output
  --limit LIMIT, -L LIMIT
                        Ignore commands longer than this.
  --env key[:val], -E key[:val]
                        Filter by shell env vars. Env vars set in RECENT_ENV_VARS as comma
                        separated list will be captured.
  --dedup, -p           Deduplication
  --time_hide, -t       dont display time in command output
  --debug, -G           Debug mode
  --detail, -l          Return detailed output
  --columns COL, -C COL
                        Comma separated columns to print if --detail is passed. Valid
                        columns are command_dt,command,pid,return_val,pwd,session,json_data
  -re, -r               enable regex search pattern
  -sql, -s              enable sqlite search pattern
  --insensitive, -i     ignore case distinctions in patterns and data

To import bash history into recent db run recent-import-bash-history
```
As for other commits, please refer to my fork for more details.

**Comment by hongyi-zhao** [comment]
Other feature enhancements I've working on:

- Regexp supports for path/pwd searching.
- Return query results according to the fields order assigned to `--columns` automatically.

**Comment by hongyi-zhao** [comment]
I currently switched to the following combination as my shell history solution, which seems more powerful and flexible and convenient:

https://github.com/dvorka/hstr
https://github.com/gawells/ariadne

Regards,
HY
